
#ifndef LIBPAS_ACP_PCF8574_H
#define LIBPAS_ACP_PCF8574_H

//#define ACP_PCF8574_CMD_PGET_INPUT 'a'
//#define ACP_PCF8574_CMD_GGET_INPUT 'b'
//#define ACP_PCF8574_CMD_GGET_DATA 'c'
#define ACP_CMD_PCF8574_GET_DATA 'o'
//#define ACP_PCF8574_CMD_PSET_OUTPUT 'e'
//#define ACP_PCF8574_CMD_GSET_OUTPUT 'f'
//#define ACP_PCF8574_CMD_PSET_DUTY_CYCLE 'g'
//#define ACP_PCF8574_CMD_GSET_DUTY_CYCLE_PWM 'h'
//#define ACP_PCF8574_CMD_GSET_DUTY_CYCLE_PM 'i'
//#define ACP_PCF8574_CMD_PSET_PWM_PERIOD 'j'
//#define ACP_PCF8574_CMD_GSET_PWM_PERIOD 'k'
//#define ACP_PCF8574_CMD_GSET_GM_DUTY_TIME_MIN 'l' 
//#define ACP_PCF8574_CMD_GSET_GM_IDLE_TIME_MIN 'm'


#endif /* ACP_PCF8574_H */

